# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import tweets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20170311_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(max_length=140, validators=[tweets.models.validate_content]),
        ),
    ]
